#!/usr/bin/env bash
#Fixes a web server to run as nginx as the nginx user listening to port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx.conf
pkill apache2
sude -u nginx service nginx start
